# Site settings
title: Lviv JavaClub
description: > #
  Let's become the best together
url: "https://www.javaclub.lviv.ua"
githuburl: https://github.com/lvivJavaClub
theme: jekyll-theme-cayman

site:
  favicon: "/assets/favicon.ico"
  
# Author information
author:
  name: "Lviv Java Club"
  email: "lviv.javaclub@gmail.com"
  
# Other
twitter_image: images/feed.jpg
paginate: 5

# Collections
collections:
  - releases

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Google services
google_analytics: UA-1596745-41
