title: Lviv JavaClub
description: > #
  Let's become the best together
url: "https://www.javaclub.lviv.ua"
githuburl: https://github.com/lvivJavaClub

theme: jekyll-theme-cayman
twitter_image: images/feed.jpg

collections:
  - releases

paginate: 5
plugins:
  - jekyll-feed

# Google services
google_analytics: UA-1596745-41
