title: Lviv JavaClub
description: > #
  Let's become the best together
url: "https://www.javaclub.lviv.ua"
githuburl: https://github.com/lvivJavaClub

theme: jekyll-theme-cayman
defaults:
  - scope:
      path: ""
    values:
      image: images/feed.jpg

paginate: 5
plugins:
  - jekyll-feed

# Google services
google_analytics: UA-1596745-41
